### ISSUE TITLE
Daemon crash when encountering accented character in desktop files

### ISSUE THREAD

**Issue by boobin** [diced/dlauncher#1]
Project built on trunk

log trace:

thread 'main' panicked at 'byte index 2 is not a char boundary; it is inside 'é' (bytes 1..3) of `Définition personnalisée pour Firefox Developer Edition`', src/fuzzy/mod.rs:69:28

**Comment by diced** [comment]
This should be fixed in https://github.com/diced/dlauncher/commit/e0d4310bba5c7d9a294b988f517830f6a60c1f30!

**Comment by dym-dym** [comment]
Sorry to re-open but I still have that issue. here's the crashing output of the daemon : 
thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside 'é' (bytes 2..4) of `Préférences du bureau`', library/core/src/str/mod.rs:127:5

**Comment by diced** [comment]
Did you rebuild dlauncher correctly and are sure that you are using the correct binary?

**Comment by boobin** [comment]
I juste rebuilt on trunk and the issue seems to be fixed on my system, at least.

**Comment by dym-dym** [comment]
My bad, I forgot I had the older binary still installed. I thought I removed it before.
